### ISSUE TITLE
建议把疲劳度30-39区间和40-49区间也区分开来

### ISSUE THREAD

**Issue by jayjayzju** [yudachi/poi#102]
如题，间宫闪和不闪的区别

**Comment by magicae** [comment]
找个颜色吧？

**Comment by Wafer-Li** [comment]
@magicae 
颜色的话直接用KCV的就差不多了

**Comment by magicae** [comment]
@Wafer-Li 给个RGB吧…

**Comment by Wafer-Li** [comment]
@magicae 
![qq 20150628174635](https://cloud.githubusercontent.com/assets/12459199/8395739/a94b658e-1dbd-11e5-9b7a-e947b00af546.png)

**Comment by magicae** [comment]
Fix in https://github.com/yudachi/poi/commit/a47f101b42e14e8f718e079409e119b4f9300b30
