### ISSUE TITLE
不能实时更新舰娘状态

### ISSUE THREAD

**Issue by Wafer-Li** [yudachi/poi#115]
版本：最新的master分支
commit SHA:82bea80072a4c4efd170097b5b59a6e9a3b55102
现象如图
![qq 20150701213809](https://cloud.githubusercontent.com/assets/12459199/8454608/c50d0fec-2039-11e5-9bee-3f0e3056ac3b.png)

对比可以发现，舰娘的状态信息更新出现了迟滞

**Comment by magicae** [comment]
console里有报错吗

**Comment by Wafer-Li** [comment]
@magicae 
![qq 20150701215119](https://cloud.githubusercontent.com/assets/12459199/8454854/5ae34210-203b-11e5-89ed-84ccf035c5be.png)
