### ISSUE TITLE
嗯，信息显示迟滞

### ISSUE THREAD

**Issue by Wafer-Li** [yudachi/poi#116]
up to the latest version
commit SHA: 9e96cf6d6d07fcb432ba958257251c0978615c4d
![qq 20150702180721](https://cloud.githubusercontent.com/assets/12459199/8473534/688634b8-20e5-11e5-889a-81e99a425c56.png)

![qq 20150702180705](https://cloud.githubusercontent.com/assets/12459199/8473531/6296a63c-20e5-11e5-9fc6-ec0eee9aafc7.png)

**Comment by magicae** [comment]
嗯知道问题了
