### ISSUE TITLE
希望增加显示海域HP

### ISSUE THREAD

**Issue by Wafer-Li** [yudachi/poi#118]
夏活快到了，说到活动，就是海域HP计量表呢！

总之，就是希望增加这么一个功能……

**Comment by Chibaheit** [comment]
等考完试..而且联合舰队也会修改

**Comment by c933103** [comment]
話說回來，在上次活動完結後不久並修改api後，按照插件kc3改作者的說法，現在各家軟件均未能支援提取聯合艦隊資料，需要等下次活動出來後才能再測試並更新

**Comment by Chibaheit** [comment]
已经添加
