### ISSUE TITLE
舰队疲劳回复时间显示有错误

### ISSUE THREAD

**Issue by zwqmoluo** [yudachi/poi#143]
点击到舰队页面之后如果刷新母港，上面显示的时间也会变长（比方剩余时间是2:40，但是一刷新之后就变回2:59了

**Comment by KochiyaOcean** [comment]
因为无法知道确切的疲劳更新时间所以目前只能每次刷新数据的时候重新估计，KCV 现在也是这样的没记错的话= =

**Comment by PHELiOX** [comment]
可以参考一下航海日志的黑科技 ＝。＝ 能准确计时

**Comment by KochiyaOcean** [comment]
航海日志那个应该是和服务器同步时间了毕竟每三分钟刷新一次=。=

**Comment by JenningsWu** [comment]
现在git版如果回到母港，舰队最低疲劳值不变的话，是不会刷新回复倒计时的。
然而看到这个issue突然意识到一个问题，如果舰队中最低疲劳值的船更换为另一艘同样疲劳值但更新时间不同的船…回复倒计时也不会刷新。

**Comment by ruiii** [comment]
可以做个id判断
应该。。不会有人更换同样疲劳值同样id的船。吧

**Comment by KochiyaOcean** [comment]
如果需要比较准确的时间的话有一个方案
因为服务器刷新疲劳的时间几乎完全确定（服务器端每分钟刷新一次）所以只要和 DMM 那边的刷新时间对照一下就行了
航海日志应该就是用的这种方法

**Comment by magicae** [comment]
航海日志的计时没问题吗？我可以去看下它代码

**Comment by magicae** [comment]
Fix by https://github.com/yudachi/poi/pull/159
