### ISSUE TITLE
优化react下的render策略，提升使用体验

### ISSUE THREAD

**Issue by JenningsWu** [yudachi/poi#146]
###### 可能应用的策略：
1. 阻止一切该节点的render。
2. 不可见时不render。可见（包括即将可见）时，若内部数据较上次更新，render。否则不render。
3. 不可见时不render。可见（包括即将可见）时，render。

---
###### 优化列表：
- [x] “概览“、”舰队“、”插件“、”设置“四个部分的管理与tab切换
  - 概览、插件、设置。三个部分呈现均不依赖父节点传入数据，外层自身也无setState调用，界面更新依赖子节点的update。应用策略1。
    - 注：各tab进一步细化优化时，会需要修改此时应用的render策略，以更新传入子节点信息。
  - 舰队。舰队面板不依赖父节点传入数据。自身包含setState。应用策略2。
* [ ] 概览面板
  - 包含多个子模块。可以传入表示该面板此时是否呈现的标识。子模块应用策略2。
* [ ] 插件面板
  - 可增加create插件时对于（非新窗口插件的）reactClass的参数，标识当前插件是否显示。若为隐藏状态，则建议插件不render以优化性能。类似策略2。
- 舰队子面板 ？
  - 目前应用策略3。若改为策略2，可加快各个舰队之间切换速度。但需要从父节点传入当前是否显示的信息，即原本应用策略1的舰队父面板，需要在切换显示/隐藏状态时render以更新传入子节点信息，从而增大四个主面板切换的开销。感觉没必要？

**Comment by magicae** [comment]
插件可以包装一下来阻止刷新

**Comment by JenningsWu** [comment]
目前来看优化到现在的性能表现已经足够了，暂时没有再做进一步优化的需要。再加上之后有可能要修改布局与结构，进一步细抠与优化可以放到以后再说。
