### ISSUE TITLE
要不要考虑同时向kancolle-db发送数据

### ISSUE THREAD

**Issue by JenningsWu** [yudachi/poi#153]
kancolle-db算是目前最成规模的第三方数据库了，虽说poi也有自己的数据库，但我觉得数据汇到一起比分散开来更好？poi的数据库可以单独用来做一些kancolle-db不支持的数据挖掘。
https://github.com/about518 ←这位大概是kancolle-db创建人？或者可以从twitter上联系他，然后协商合作&要个数据接口？

**Comment by PHELiOX** [comment]
之前提出过，好像赞同不多

**Comment by c933103** [comment]
#78
