### ISSUE TITLE
任务列表中未完成日常任务的跨日清理

### ISSUE THREAD

**Issue by liruizhe** [yudachi/poi#162]
/views/components/main/parts/task-panel.cjsx里面的逻辑是这样的：

![2015-07-13 2 14 06](https://cloud.githubusercontent.com/assets/1358270/8643671/8a8a8bfe-2969-11e5-9b4d-fb57d08798f5.png)

因为这里是不断刷新的，如果机器一直开着是没问题的。

但是在不少人的使用习惯里面，夜晚不关游戏但是休眠机器，第二天起床后将机器从休眠中唤醒。

但是如果唤醒机器的时候是北京时间8点以后，curHours就从0开始了，从而不满足curHours >= 20的条件，这样前一天没有完成的日常任务不会清理掉。

**Comment by magicae** [comment]
……………………………………………………………
