### ISSUE TITLE
经验计算选择舰娘点开一片白

### ISSUE THREAD

**Issue by shabaoAI** [yudachi/poi#166]
只有空是显示的 背景一片白是BUG么？
鼠标移动的时候才能看到舰娘名字

**Comment by magicae** [comment]
主题的问题
cc @ruiii @KochiyaOcean

**Comment by shabaoAI** [comment]
现在还没办法更换吗？

**Comment by ruiii** [comment]
环境是windows吗？

**Comment by shabaoAI** [comment]
win7

**Comment by ruiii** [comment]
使用的poi版本号是？

**Comment by Wafer-Li** [comment]
@magicae 
Since it has been merged, how to update to fix the bug?

**Comment by KochiyaOcean** [comment]
进 resources/app/assets/themes/paperdark/css/paperdark.css 覆盖原文件

**Comment by Wafer-Li** [comment]
@KochiyaOcean 
I see.

**Comment by magicae** [comment]
Fixed.
