### ISSUE TITLE
网络正常时也会提示“网络连接失败“

### ISSUE THREAD

**Issue by gnattu** [yudachi/poi#172]
就像图里这样，进入母港后几秒钟下方的信息条就开始提示网络连接失败。使用的是http代理连接到局域网内的服务器。游戏功能一切正常
![Image of error]
(http://ww4.sinaimg.cn/large/bc69e012gw1eu2rt539f1j20ma02qq3w.jpg)
![Image of proxy]
(http://ww2.sinaimg.cn/large/bc69e012gw1eu2rvz39bhj20d70bzjs4.jpg)
系统环境osx 10.11

**Comment by PHELiOX** [comment]
跟我一样，不过只有游戏开始时候显示，另外导致自适应很慢。

**Comment by KochiyaOcean** [comment]
应该是某些页面元素载入失败引起的

**Comment by magicae** [comment]
不是这个导致自适应很慢的 是因为有些东西在你的网络状态下访问超时了…自适应的时刻取决于最后一个网页的包
