### ISSUE TITLE
主题显示问题

### ISSUE THREAD

**Issue by Wafer-Li** [yudachi/poi#179]
win 7
electron-v0.30.0-win32-ia32
commit SHA: 4fee2f28b1013dff7a24b75b8c11647e30c8fdbb

Paperdark 主题下，任务信息插件的分类 **【可执行】** **【未开放】** **【已完成】** 依旧反白

**Comment by magicae** [comment]
Fixed by https://github.com/ruiii/poi_theme_paper_dark/pull/12
