### ISSUE TITLE
希望可以自己设置首页...

### ISSUE THREAD

**Issue by taroxd** [yudachi/poi#180]
毕竟我比较习惯用 token 直连登录。
就像改 kcv 的 KanColleViewer.exe.config 一样，我希望 poi 也可以设置一下打开的首页呢。应该不难吧，谢谢啦

**Comment by magicae** [comment]
难 poi目前的首页是写死的。。。

**Comment by KochiyaOcean** [comment]
如果不嫌麻烦的话就请去 resources/app/index.html 里手动改一下吧

**Comment by magicae** [comment]
嗯对  resources/app/index.html 里有一个webview src="..." 里面的地址自己改掉就好

**Comment by taroxd** [comment]
不嫌麻烦，毕竟 kcv 也是这个姿势。谢谢啦~
