### ISSUE TITLE
Bug in main view

### ISSUE THREAD

**Issue by myzWILLmake** [yudachi/poi#29]
The num of slot_item doesn't change.
A way to solve this issue is in the last commit of my branch.
@magicae

**Comment by myzWILLmake** [comment]
Another problem: Remodel packages
The packages  of "改修工厂" are not catched, which would reduce the num of slot items.
Example:
To remodel a "46cm三連装砲" slot item, I need to pay another "46cm三連装砲" which is random chosed(?).

I will try to solve this issue.

**Comment by magicae** [comment]
It is hard to catch this response...
