### ISSUE TITLE
OS X版游戏内时间显示有误

### ISSUE THREAD

**Issue by PhoenixEmik** [yudachi/poi#56]
大概显示成了UTC...
![2015-06-13 12 04 12](https://cloud.githubusercontent.com/assets/10204811/8142929/5545fcec-11c4-11e5-8252-1630010f2cdd.png)

**Comment by magicae** [comment]
Related upstream issue: https://github.com/atom/electron/issues/1784
Won't fix until Electron fixed.

**Comment by magicae** [comment]
Fixed by https://github.com/atom/electron/pull/2105

**Comment by magicae** [comment]
Fixed by https://github.com/atom/electron/pull/2105
