### ISSUE TITLE
希望能更改字体

### ISSUE THREAD

**Issue by xiaozhikang0916** [yudachi/poi#57]
现在的字体太花哨看得很累，希望能改为系统默认字体或者允许自选字体

**Comment by magicae** [comment]
poi 没有内置的字体，按照每个主题的配置自动选择的系统字体。

**Comment by xiaozhikang0916** [comment]
已找到原因，我（和我同学）都装了小圆剧场版外挂字幕的某个字体，poi默认选到了这个字体，我把雅黑提到最前就好了

**Comment by magicae** [comment]
嗯嗯好的
