### ISSUE TITLE
一些bug

### ISSUE THREAD

**Issue by PHELiOX** [yudachi/poi#58]
1. 改修如果吃掉舰队中的船，舰队信息不会立刻刷新，而是返回母港才刷新。
2. mac下的缓存包要放在包中MacOS下才能生效，而且缓存文件不会被更新。
3. 远征计时器没有按照当前时间进行计算，似乎是按照母港信息刷新的。如果开着poi系统睡眠，再开机时剩余时间会不更新。

**Comment by magicae** [comment]
1. 会在之后的更新中 Fix
2. poi 作为一个基本浏览器，目前不打算接管缓存维护之类的事情，所以对缓存包的支持只在“使用”而不是“维护”。为了方便起见，Mac OSX的缓存位置会在之后转到 ~/Application Support/ 下，但是短时间内同样不会被维护。

**Comment by PHELiOX** [comment]
不知道chrome有办法将缓存保存为文件夹的形式而不是chrome本身的文件格式吗

**Comment by magicae** [comment]
@PHELiOX 目前不知道…

**Comment by sxc12341** [comment]
建议@magicae建一个技术群方便开发交流经验，再建一个水友群用作测试宣传用

**Comment by xiuluo** [comment]
岛风go的缓存文件应该放哪？

**Comment by xiuluo** [comment]
@magicae  岛风go的缓存文件应该放哪？

**Comment by magicae** [comment]
@sxc12341 378320628

**Comment by magicae** [comment]
@xiuluo 
Win, Linux 软件目录根目录下
Mac 目前比较麻烦 等待版本更新吧

**Comment by xiuluo** [comment]
@magicae 我之前用的是kcv的缓存插件的缓存文件，目录格式为/MyCache/kcs/，这样的，需要怎么改目录？

**Comment by PHELiOX** [comment]
加了第三条，倒计时器的问题

**Comment by magicae** [comment]
@PHELiOX will fix

**Comment by magicae** [comment]
@xiuluo Win和Linux直接放在 poi 根目录的 cache
