### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by PHELiOX** [yudachi/poi#59]
1. 第一舰队添加泊地修理计时器
2. 防猫功能添加手动重试选项
3. 任务进度最好显示具体击破数字，比如a号和ro号任务
4. 剧透插件最好计算一下战斗结果B胜C败
5. 剧透插件显示每艘船的炮击伤害
6. 剧透插件显示双方飞机击落数，我方当前制空值
7. 剧透插件在演习时计算获得经验值
8. 使用插件自定poi的界面，比如同时显示母港和舰队信息，修改字体和颜色
9. 添加关闭声音功能

**Comment by magicae** [comment]
防猫功能的设置接口之后的更新会添加。
关闭声音 Electron 不支持，等待上游更新。
关于插件的讨论到各个插件的 issue 中讨论，暂时 Close。

**Comment by PHELiOX** [comment]
@magicae 需要在手动搬运一次吗

**Comment by magicae** [comment]
嗯，剧透插件在 https://github.com/yudachi/plugin-prophet
记得@插件开发者 @Chibaheit

**Comment by PHELiOX** [comment]
@magicae 自定义界面布局，目前能实现吗，通过插件

**Comment by magicae** [comment]
难… 靠 HTML+CSS 自定义布局挺难的，不像Native UI…
