### ISSUE TITLE
OSX的入渠和劇透插件

### ISSUE THREAD

**Issue by EtherZ** [yudachi/poi#60]
Yosemite10.10.3
1. 入渠後不會馬上刷新，需要返回母港後才會刷新狀態
2. 戰鬥結束後回到地圖界面時，受到損傷的船的血條恢復到未損傷的狀態，進入下一個點後又恢復實時狀態。
這個bug只在第一次使用這個插件去打4-5時出現過一次，觸發條件不明。
3.佈局切換時窗口似乎無法自動適應遊戲部分，會出現一個這樣的留白
![image](https://cloud.githubusercontent.com/assets/4509997/8143382/ce80b016-11e2-11e5-84c8-e020abe3e09f.png)
主要出現在縱→橫的時候，偶爾橫→縱也會。
需要手動拉一下窗口才會恢復。

然後是幾個UI在細節上希望的改進。
+遊戲最下方的信息條感覺不到必要性，也許是測試時留下的。
+所有的主題概覽的最下面這種地方沒和遊戲窗口對齊，強迫症看著略鬧心
![image](https://cloud.githubusercontent.com/assets/4509997/8143385/4baa6000-11e3-11e5-8173-c6c92bf70cb9.png)
+即使是不同主題的不同字體，希望把字的大小統一一下。Paper太大，Lumen太小。
+把信息欄的寬度固定。不然在遊戲分辨率改變時由於窗口大小沒變，就會這樣……
![image](https://cloud.githubusercontent.com/assets/4509997/8143398/b2bd196c-11e4-11e5-82c0-b0db83662825.png)
必須手動調整。

順帶期待劇透插件以後能有顯示戰鬥結果和大破警告和顯示交戰形態等等的功能。

感謝在OS X上出了一個這樣的工具，沒有能力做開發，只能精神上支持。

**Comment by magicae** [comment]
界面布局方面会持续调整。各个主题字体问题是各个主题其实包括了一套字体设置，不便覆盖。
大破警告内置就有。
> 戰鬥結束後回到地圖界面時，受到損傷的船的血條恢復到未損傷的狀態，進入下一個點後又恢復實時狀態。
是 poi 主体的问题还是插件的血条？

**Comment by EtherZ** [comment]
看來我沒找到大破警告在哪，用了poi後果然穩如poi次次出擊都大破而歸但是並沒有收到什麼警告？

插件的血條。
不過我當時盯著插件在看，也沒注意主體的艦隊下怎麼顯示的。切來切去確實比較麻煩。

**Comment by magicae** [comment]
归港没有警告 只有真正大破进击的一刻才有警告

**Comment by magicae** [comment]
插件的血条问题可以反馈给各个子插件，链接在项目主页有

**Comment by Chibaheit** [comment]
血条问题正在测试..无法重现

**Comment by magicae** [comment]
UI 的问题会持续关注，跨平台下对齐问题可能做不到。
剧透插件的问题等待插件更新，讨论移至插件 issue。
Close issue。
