### ISSUE TITLE
任务列表bug

### ISSUE THREAD

**Issue by PHELiOX** [yudachi/poi#61]
前一天的任务如果未完成，任务刷新后应该消失的任务仍然在列表中，而且不会被去掉。
只能重启poi进行刷新。

p.s. 似乎每条bug分立issue比较好？

**Comment by magicae** [comment]
因为不能辨认日常周常，每天到点自动清空所有任务可以吗？

**Comment by PHELiOX** [comment]
@magicae 我以为点击任务以后只要重新用服务器端的任务列表刷新一下当前任务列表就好了 ＝。＝

**Comment by magicae** [comment]
目前就是这么做的，但是不同天的日常编号也不一样。

**Comment by PHELiOX** [comment]
@magicae 呃，刷新的话不是应该去掉旧的列表再显示新列表吗，跟具体的任务有关系？或许可以参考一下74eo，他的任务记录不仅实时更新，还可以显示详细的进度。

**Comment by magicae** [comment]
详细进度 poi 主体没有空间弄这个了，等插件吧。刷新的话目前是按照任务 ID 的，如果有一样的 ID 才会去掉旧的，然而不同天的同样日常 ID 是不一样的…………

**Comment by magicae** [comment]
目前打算是换日清空列表

**Comment by magicae** [comment]
改成了换日清空日常
