### ISSUE TITLE
有没有远征归来时的提醒功能呢

### ISSUE THREAD

**Issue by imomo** [yudachi/poi#62]
远征回来的时候没有像kcv那样的提醒感觉很麻烦呢。。

**Comment by magicae** [comment]
Linux 和 Mac 下一直都有 但是 Windows 上由于 Electron 的原因不支持。

**Comment by imomo** [comment]
唔。。有办法解决么。。

**Comment by magicae** [comment]
目前没办法。。

**Comment by magicae** [comment]
Fix it by change notify dependency. Wait next release.
