### ISSUE TITLE
希望能增加选项完全固定游戏界面在左上角不受放大缩小程序影响

### ISSUE THREAD

**Issue by moondigi** [yudachi/poi#63]
强迫症患者
程序界面高度太小拖大后看资料，然后左边游戏也跟着上下移动
想将程序高度缩回去最小高度触摸屏又缩不准，令到游戏也缩了一下满屏狗牙
能不能强制固定游戏分辨率800x480在左上角，不管程序怎么缩放都不会动到游戏？

**Comment by moondigi** [comment]
程序希望也能增加一个按钮开关声音，使用游戏内的那个调整不够迅速，使用系统自己的调整在用splashtop远程的时候经常出问题

**Comment by malichan** [comment]
强制游戏固定分辨率的功能现在就有呀，只是不是在左上角而是左侧居中而已。

**Comment by moondigi** [comment]
不希望居中，而且程序高度太小的话也会导致游戏缩放，希望能稳定固定游戏在左上角不受程序界面影响
刚刚试了一下右边程序界面滚动的时候有时也会令左边游戏一起滚动

**Comment by moondigi** [comment]
![1](https://cloud.githubusercontent.com/assets/8404678/8147325/23ea4940-1297-11e5-9a90-a11fcaca7ebd.gif)

**Comment by magicae** [comment]
现在设置里有固定分辨率功能，大小和位置可以自己调节
