### ISSUE TITLE
猫后一键刷新功能

### ISSUE THREAD

**Issue by zhudhjen** [yudachi/poi#64]
很多时候猫了要跑到设置里去刷新，不知道能不能识别出猫的状态？并且在界面上加入刷新按钮？

**Comment by magicae** [comment]
目前不能识别出猫的状态 有防猫功能 假如猫率太大可以试试

**Comment by magicae** [comment]
界面上加刷新按钮可能会导致误触，目前依然准备保留仅仅在设置中点击的方式
