### ISSUE TITLE
幾點意見…

### ISSUE THREAD

**Issue by c933103** [yudachi/poi#78]
1.多語界面支援或者潛在支援能力
2.Cookie直連支援
3.多開艦Colle支援或潛在支援能力
4.kancolle-db整合支援
5.收集所得數據在哪看？
6.建議考慮把防貓重試值預設為0
7.有人反映看不順眼帳戶名是yudachi而不是yuudachi或者yūdachi

**Comment by KochiyaOcean** [comment]
4、kancolle-db 的数据提交需要从 twitter 获取 key，成本太高；
5、收集数据中敌阵型在未卜先知插件中可以看到（进入战斗之前），其他数据尚未开放（因为暂时没时间写网页）
6、已经是 0 了
7、yuudachi 已经被占用了 Orz

**Comment by c933103** [comment]
2.我指的是http://zh.moegirl.org/舰队Collection/如何连线#.E6.94.B9Cookie
4.從twitter獲取key只需要想提交數據的用戶自己獲取…

**Comment by magicae** [comment]
F12功能下版本会加入
KanColle-db没有打算

**Comment by KochiyaOcean** [comment]
呃其实有需求的话可以试着自己开发一下……
