### ISSUE TITLE
展示全部任务信息的插件

### ISSUE THREAD

**Issue by Wafer-Li** [yudachi/poi#79]
既然都有了“远征信息”插件，为何不能来一个“任务信息”插件？

这里指的不是显示当前做的任务，而是类似“远征信息”一样展示对各个任务的准备情况和必要条件。

**Comment by myzWILLmake** [comment]
没记错的话有是正在开发的一个插件 估计很快就能看到了

**Comment by malichan** [comment]
现在就有啊。。如果你是使用2.0.0+的话，把鼠标放在任务面板的条目上试试。。

**Comment by Wafer-Li** [comment]
所以我指的不是显示当前任务，而是类似全任务表一样的功能

**Comment by magicae** [comment]
@malichan 全列表有打算吗？

**Comment by malichan** [comment]
以后可能会做，但优先级不是特别高（主要是考虑到用户对自己没有接的任务应该不会特别感兴趣）。会先把现在的插件改善的稳定一些。

**Comment by magicae** [comment]
@malichan 嗯 成本确实比较高

**Comment by KochiyaOcean** [comment]
我在一心二用里加个 wiki 的链接以方便查看如何

**Comment by KochiyaOcean** [comment]
一心二用追加了快捷链接功能，其中包括 wiki 的链接，在没有专用插件之前先将就一下吧……

**Comment by Wafer-Li** [comment]
对于“用户对自己没有接的任务并不是很感兴趣”，这点在很多情况是不成立的。

首先，舰娘最多只能接5个任务的奇葩设定，导致了不能一次性接完任务来做，所以，需要全任务表来对任务优先级来进行规划，并不是说用户不接这个任务就是不想做这个任务。

其次，舰娘很多重要任务，比如说周常拿运输桶的任务、一式弹任务等等，均存在前置任务，然而如果不知道其前置任务是什么，就不知道如何开出这个任务来做，这个时候就要使用全任务表对任务的完成流程做出规划。

总之，全任务表就是帮助用户实现一个中长期规划的功能，并不是仅仅限于“所接的任务”。
当然，为了实现这样的一个规划功能，全任务表只是一种形式而已，如果有其他更好的形式也可以。

**Comment by KochiyaOcean** [comment]
显示包括一次性任务的全任务树结构等等还是太复杂了，短时间内还是考虑用一心二用开 wiki 页面解决吧……

**Comment by malichan** [comment]
任务插件1.0.0版已经可以显示全部任务的信息了，欢迎试用。
https://github.com/yudachi/plugin-quest/releases/tag/v1.0.0
