### ISSUE TITLE
舰队制空值始终为0

### ISSUE THREAD

**Issue by Wafer-Li** [yudachi/poi#85]
版本为git到的最新版本

目前仅在WINDOWS下测试出现这个问题，Linux 和 OS X 未知

望解决

**Comment by Chibaheit** [comment]
因为新式算制空值会为负数,所以和0取了个max

**Comment by Wafer-Li** [comment]
![qq 20150622221639](https://cloud.githubusercontent.com/assets/12459199/8282525/6418a7c8-192c-11e5-9dae-9253c001df2f.png)
再怎么说这种配置也不可能是0的，而且制空值计算公式并没有更新，原公式不会出现为负数的情况

**Comment by Chibaheit** [comment]
不是的 按新的算法 会出现负数.航海日志用的是旧公式..

**Comment by Wafer-Li** [comment]
这个是Wiki上的制空值计算公式，据我了解，自2014春活以来，并没有出现制空值计算的任何变动。不知道你所指的是不是索敌值计算公式。
![qq 20150622232553](https://cloud.githubusercontent.com/assets/12459199/8284183/926c3e32-1936-11e5-8554-29b2710b5ef0.png)
