### ISSUE TITLE
OS X版更新 v2.1.0 版后远征信息插件无效的问题

### ISSUE THREAD

**Issue by willtse** [yudachi/poi#87]
今天更新了v2.1.0 版，发现远征信息插件中“舰队准备情况”、“远征收支”、“必要条件”等都没的信息显示了......
![poi](https://cloud.githubusercontent.com/assets/328654/8304967/3c697c96-19dd-11e5-9278-7b92820817a5.png)

**Comment by magicae** [comment]
你还没点下面的按钮吧？

**Comment by willtse** [comment]
点了的...我重装下看看...
![6 23 2015 20 01](https://cloud.githubusercontent.com/assets/328654/8305566/eec45186-19e2-11e5-8c9e-48dc34b359aa.gif)

**Comment by malichan** [comment]
咦，我这里并没有问题啊。。。你把开发人员工具打开，切到Console那一页，把错误信息发一下吧。。。

**Comment by willtse** [comment]
问了下我朋友，他2.1.0版本也是这个问题，之前的版本没问题。
![developer_tools](https://cloud.githubusercontent.com/assets/328654/8306112/e7b4a864-19e7-11e5-97c5-2761ffc860a8.png)

**Comment by malichan** [comment]
你是不是有舰队没有开放？如果是的话我可能知道原因了。

**Comment by willtse** [comment]
嗯...才入坑不久，第4舰队还没开...

**Comment by malichan** [comment]
远征插件的1.2.1版应该可以解决，但我没有小号没法测试…… 
https://github.com/yudachi/plugin-expedition/releases/tag/1.2.1

**Comment by willtse** [comment]
我试了一下没问题了，十分感谢~！
