### ISSUE TITLE
关于WIN下的进程和UI的建议

### ISSUE THREAD

**Issue by AkaiSky** [yudachi/poi#97]
1.windows环境下同时存在多个进程，似乎表明程序是模块化的？不知道能不能整合一下
2.右侧窗口在拉伸过后会出现字体较小的情况，另外下方留白较多，建议右侧信息栏可调整字体和窗口大小
3.点击开发人员工具后页面适配失效，不过似乎最新版的自动适配窗口按钮已经解决此问题，但还是建议将入口移动到侧边栏

**Comment by AkaiSky** [comment]
追加一个，目前发现打开插件时可能存在新开窗口白屏的问题，重新启动程序后问题解决，具体原因不明

**Comment by magicae** [comment]
1. 不能
2. 可以用自定义CSS
3. 这个是 Electron 的问题
4. 这个是插件的问题 https://github.com/yudachi/plugin-Akashic-records/issues/2
